### PR TITLE
chore(package): update async to version 2.0.0

### PR DESCRIPTION
**Pull request by jdalton**
https://greenkeeper.io/

### CODE REVIEW

**Comment by jdalton** [comment]
\@megawac That's right, `babel-plugin-lodash` works with `async` 2.0 ‼️

**Comment by jdalton** [comment]
https://github.com/lodash/babel-plugin-lodash/blob/master/test/mixed-fixtures/async-bound-ramda/expected.js

**Comment by megawac** [comment]
Sweetness

**Comment by jdalton** [comment]
You just specify the [additional module ids](https://github.com/lodash/babel-plugin-lodash/blob/master/test/mixed-fixtures/async-bound-ramda/options.json) you'd like it to scan for.

```json
{
  "plugins": [["lodash", { "id": ["async", "lodash-bound", "ramda"] }]],
  "presets": ["es2015"]
}
```

**Comment by jdalton** [comment]
It's approaching the time to split it out into a more generic tree-shaking plugin,

**Comment by megawac** [comment]
Cool and would this plugin just extend the plugin to add support for `fp` and erring on `chain`? if so that'd be rad

**Comment by jdalton** [comment]
> Cool and would this plugin just extend the generic plugin to add support for `fp` and erring on `chain`? if so that'd be rad

Ya, that would be the plan.

**Pull request merged**
