### PR TITLE
Marks 'babel-helper-module-imports' as a non-dev dependency

### LINKED ISSUE #199: Running into "Cannot find module 'babel-helper-module-imports'" on 3.3
I believe the cause is marking "babel-helper-module-imports" as a devDependency when it's being called in "src/importModule.js"

### PR DESCRIPTION
**Pull request by medanat**
Fixes #199

### CODE REVIEW

**Comment by CentaurWarchief** [comment]
I think you'll also need `lodash-compat`. Just ran into the same issue here :(

**Comment by medanat** [comment]
@CentaurWarchief You're right, it's the next issue down the line. I've updated the PR to include `lodash-compat`.

**Comment by antixrist** [comment]
@medanat without `lodash-es` the same error occur

**Comment by jdalton** [comment]
Patched https://github.com/lodash/babel-plugin-lodash/commit/04e2fda207816ebd29615559a7a639e34274010f.

**Comment by antixrist** [comment]
@jdalton without `lodash-es` or `lodash-compat` in `dependencies` I still have following errors:
`Module build failed: Error: Cannot find module 'lodash-es'`
`Module build failed: Error: Cannot find module 'lodash-compat'`

**Comment by jdalton** [comment]
Show me where in the production source those packages are referenced. The [Babel 7 compat PR](https://github.com/lodash/babel-plugin-lodash/pull/194/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) only added 2 deps.

**Comment by medanat** [comment]
@jdalton From my understanding, I believe the `ModuleCache.resolve` method in https://github.com/lodash/babel-plugin-lodash/blob/master/src/ModuleCache.js#L41 tries to require/import them given those packages are listed as the default in https://github.com/lodash/babel-plugin-lodash/blob/master/src/config.js#L7

**Comment by antixrist** [comment]
@jdalton Those errors thrown from node's `module`:
https://github.com/nodejs/node/blob/82790d84f2049cdd5e9aac4818a096834bed0118/lib/module.js#L540-L545
because you [try to resolve](https://github.com/lodash/babel-plugin-lodash/blob/d6ddc7083bdeaacc5fb71621942d19e4a3678553/src/ModuleCache.js#L42-L44) [all `defaultsIds`](https://github.com/lodash/babel-plugin-lodash/blob/master/src/config.js#L25).
But `lodash-es` and `lodash-compat` not installed because they not included in 'dependencies'

**Comment by jdalton** [comment]
That's not how that should work

**Comment by antixrist** [comment]
@jdalton error's stacktrace has shown that it works completely so as I described

**Pull request closed without merging**
