### PR TITLE
Support explicit, terminated chain sequences.

### PR DESCRIPTION
**Pull request by mickylad**
This does some work towards #92 - I've not had time yet to figure out if or how unterminated chains might be handled, as well as imlpicit chains.

Would be good to know if this is something you'd be willing to merge, I know you said you would accept a PR on #92 but obviously this doesn't cover all cases, at least yet.

If you do have thoughts on how unterminated and implicit chains could be handled, I'd be glad to hear them and see if I can make any more progress.

### CODE REVIEW

**Comment by jdalton** [comment]
Whoa! So awesome! 🎉

**Comment by lukeapage** [comment]
I'd be happy to see this merged as is, we could start using the plugin but we would enforce no unterminated or implicit chaining.

Does it need rebasing? Looks like it picked up unintentional commits.

**Comment by mickylad** [comment]
Ah yes, will rebase!

**Comment by mickylad** [comment]
Rebased

**Comment by lukeapage** [comment]
@jdalton any chance of getting this merged or reviewed soon?

**Comment by jdalton** [comment]
Hi @lukeapage!

I have my head down with the WIP [esm loader](https://github.com/standard-things/esm) at the moment.

**Comment by adierkens** [comment]
Any update on this?

**Comment by laander** [comment]
Bump on this, would be amazeballs to get out! ⚡️

**Comment by rkrueger11** [comment]
what about now? 😁

**Comment by mickylad** [comment]
@jdalton I've pushed an up-to-date version of this. I noticed you've updated your code style - I tried to bring my changes inline with that, so let me know if there's anything I've missed!

**Comment by jdalton** [comment]
@mickylad Thank you! Yeah, my code style tends to change based on the last project I worked on. There is now a clash of styles I'll be dealing with 😋

**Comment by mickylad** [comment]
I know the feeling! Thanks! :)

**Comment by hipstersmoothie** [comment]
Can we get a release?

**Comment by hipstersmoothie** [comment]
are we gonna get a release in 2018? @mickylad @jdalton @anyone-who-cares

**Comment by lukeapage** [comment]
I care.. am waiting to use it, though if I get the time I will just publish it privately, so this is an annoyance but not a blocker.

**Comment by alisowski54** [comment]
@lukeapage @mickylad @laander @rkrueger11 PR was reverted :(

**Comment by jdalton** [comment]
Even thought it was ultimately reverted I'm very thankful to @mickylad for putting the time into this PR!

Related to https://github.com/lodash/babel-plugin-lodash/issues/210#issuecomment-392961984.

**Pull request merged**
