### PR TITLE
JSX expressions

### LINKED ISSUE #87: JSX expressions are not always transformed correctly.
I noticed that if I am using `babel-plugin-incremental-dom` and `babel-plugin-lodash` together, and I do something like this:

```js
import {noop} from 'lodash';

const myNoop = noop;

console.log(noop);

function render() {
  return <div onClick={noop} />;
}
```

...it will be transpiled to this:
```js
'use strict';

var _noop2 = require('lodash/noop');

var _noop3 = _interopRequireDefault(_noop2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var myNoop = _noop3.default;

console.log(_noop3.default);

function render() {
  return elementVoid('div', null, null, 'onClick', noop);
}
```
which will throw a `ReferenceError` for `noop`.

I think the reason it works with React is because the JSX attributes are passed as an object to `createElement`, and the `Visitor` has a case for `ObjectProperty`. Removing `ObjectProperty` causes transpiled React code to have the same error.

Adding something like this to the `Visitor`:
```js
    'JSXExpressionContainer': replaceNode('expression'),
```
seems to work, but I'm definitely not sure about that being the correct solution.

Thanks!

### PR DESCRIPTION
**Pull request by mthadley**
Resolves #87.

Hopefully these are the kind of tests you are looking for.

Thanks!

### CODE REVIEW

**Comment by jdalton** [comment]
These tests are fantastic. Does the incremental plugin support Node 0.12? It's [failing it's Travis run](https://travis-ci.org/lodash/babel-plugin-lodash/jobs/144321806).

**Comment by mthadley** [comment]
Apparently not, looks like it's failing because of a call to `Object.assign`.

**Comment by megawac** [comment]
Do we need incremental-dom in this case? Can we not just ensure that babel-plugin-lodash supports transforming code inside of JSX expressions?

I.e. the test would expect actual to be 

```
function render() {
  return <div onClick={_noop3.default} />;
}
```

**Comment by mthadley** [comment]
@megawac Yes, that makes a lot of sense. We would also only need to bring in `babel-plugin-syntax-jsx` that way.

**Comment by jridgewell** [comment]
I'd recommend not requiring `babel-plugin-incremental-dom` (I dropped `v0.12` for `Object.assign`, though I that's reverted in an unreleased commit).

**Comment by jdalton** [comment]
Cool cool.

**Pull request merged**
