### PR TITLE
Adds support for lodash v4.0.0 by including the lodash root dir in fu…

### PR DESCRIPTION
**Pull request by corbanbrook**
…nction resolving. Also filters out non .js files from categoryMap

### CODE REVIEW

**Comment by corbanbrook** [comment]
Fixes #22

**Comment by jdalton** [comment]
Hey @corbanbrook!

I know this is a bit after the fact but could you sign the [jQuery Foundation CLA](https://contribute.jquery.org/CLA/) if you haven't already.

**Comment by corbanbrook** [comment]
@jdalton done.

**Comment by jdalton** [comment]
Thank you!

**Pull request merged**
