### PR TITLE
Quit swallowing errors while trying to find modules

### PR DESCRIPTION
**Pull request by danny-andrews**

### CODE REVIEW

**Comment by danny-andrews** [comment]
The `} catch (e) {}` made it really difficult to track down an error where the `main` field in `package.json` was set to a file that didn't exist because I hadn't built it yet.

**Comment by jdalton** [comment]
Thank you!

**Comment by jdalton** [comment]
@danny-andrews I had to revert this PR because it was causing errors (#202)

**Comment by danny-andrews** [comment]
I guess we should figure out what "expected" errors are and what "unexpected" errors are and only swallow the former.

**Pull request merged**
