### PR TITLE
adds prepublish script

### PR DESCRIPTION
**Pull request by boneskull**
see #45

### CODE REVIEW

**Comment by jdalton** [comment]
Hi @boneskull!

Have you signed [our CLA](https://contribute.jquery.org/CLA/)?

**Comment by boneskull** [comment]
@jdalton No thanks.  I'm sure you guys can manage this one.

**Comment by megawac** [comment]
@boneskull do you mind signing it actually for #43

**Comment by jdalton** [comment]
@boneskull See https://infrequently.org/2008/06/why-do-i-need-to-sign-this/

**Comment by boneskull** [comment]
Don't want to be a pain in the ass about this, but:

- nowhere is a signing a CLA mentioned in this repo
- if there was such a notice I would not have contributed
- I won't sign a CLA for code you've already merged
- I'm not really eager to debate my reasons why not in a public forum at the moment.

@jdalton I received your email on the matter and will reply sometime today. @megawac if you wish to be cc'd please let me know.

**Comment by megawac** [comment]
No thanks, but I can understand where you're coming from. IANAL so I hate
signing these documents and would never sign one like Google's CLA which
includes domains outside of contributing to OSS such as conversation. That
being said, the jQuery CLA isn't a scary one from my understanding of it.

**Comment by jdalton** [comment]
@megawac Can you revert the previous code you merged.
We need to tackle it without @boneskull's contribution.

**Comment by jdalton** [comment]
CLA's are covered in our [contributing](https://github.com/lodash/babel-plugin-lodash/blob/master/.github/CONTRIBUTING.md) text btw.

**Comment by jdalton** [comment]
I reverted it.

**Comment by megawac** [comment]
The commit is still in a) the repo and b) on npm. Further, this reverts a
fix for real bug. I don't know how to address this situation.

On Sat, Apr 16, 2016 at 7:52 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
Yep, that's fine. We'll revert and implement our own way. You can do this by tackling the issue without basing it off the reverted patch.

**Comment by jdalton** [comment]
Christopher Hiller (@boneskull) signed the CLA (4/29/2016 15:44:33)

**Pull request closed without merging**
