### PR TITLE
Don't cache nodes

### PR DESCRIPTION
**Pull request by jridgewell**
Also, avoid an entire Program traversal to gather the imports.

### CODE REVIEW

**Comment by jdalton** [comment]
Thanks @jridgewell!

I think this is a bit too aggressive at the moment. I'm prepping a patch for this which is a little less.

**Comment by jridgewell** [comment]
Which part was too aggressive? This had a pretty good perf boost in it.

**Comment by jdalton** [comment]
You can compare the two versions (yours vs the patched hash above to see the difference).

**Comment by jridgewell** [comment]
So the perf improvement. 😛

**Comment by jdalton** [comment]
Hmm, I'll review that bit tonight.

**Pull request closed without merging**
